language: 
    - node_js
    - go
go: 
    - "1.14"
node_js:
    - 12.16.3
    - "14.2.0"
cache:
    directories:
        - node_modules
script:
    # - rm ./package-lock.json
    - yarn install
    - yarn run build
    # - yarn add now@latest
    - now --token=$NOW_TOKEN -c
    # - now dev --token=$NOW_TOKEN

