language: 
    - node_js
    - go
go: 
    - "1.14"
node_js:
    - "14.2.0"
cache:
    directories:
        - node_modules
script:
    - rm ./package-lock.json
    - yarn run build
    # - yarn add now@latest
    - now --token=$NOW_TOKEN -c
    - now dev

